import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
assert.equal(process.env.TEST_ISOLATED_PREVIEW,'1');
const base=process.env.APP_URL,out=process.env.ARTIFACT_DIR;await mkdir(out,{recursive:true});
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const browser=await chromium.launch({headless:true,channel:'chrome',args:['--enable-unsafe-swiftshader']}),context=await browser.newContext({viewport:{width:1760,height:1160},acceptDownloads:true}),page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());const report={checks:[]};
try{
 const a=await context.request.post(`${base}/api/v1/auth/login`,{data:{username:'demo',password:'demo1234'}});assert.ok(a.ok());const token=(await a.json()).access_token,headers={Authorization:`Bearer ${token}`};
 const call=async(method,path,data)=>{const r=await context.request[method](`${base}/api/v1${path}`,{headers,data});assert.ok(r.ok(),await r.text());return r.json()};
 const p=await call('post','/projects',{code:'DIRECTOR-'+Date.now(),name:'导演台验收 · 布景与运镜'}),root=`/projects/${p.id}`;report.project=p.id;
 const script=await call('post',root+'/scripts',{title:'双人对话'});await call('post',root+`/scripts/${script.id}/apply-scenes`,{scenes:[{title:'室内对话',shots:[{title:'窗前双人中景'}]}]});report.shot=(await call('get',root+'/shots'))[0].id;
 await context.addInitScript(t=>{localStorage.setItem('inspiration_token',t);localStorage.setItem('inspiration_lang','zh')},token);
 await page.goto(`${base}${root}/director`);await page.getByRole('button',{name:'新建预演',exact:true}).click();await page.getByLabel('预演名称',{exact:true}).fill('窗前对话 · 推近预演');await page.getByRole('button',{name:'室内场景',exact:true}).click();await page.getByRole('button',{name:'人物 A',exact:true}).click();await page.getByLabel('位置 X',{exact:true}).fill('-1.5');await page.getByRole('button',{name:'撤销预演修改',exact:true}).click();assert.equal(await page.getByLabel('位置 X',{exact:true}).inputValue(),'-1.1');await page.getByLabel('位置 X',{exact:true}).fill('-1.5');await page.getByRole('tab',{name:'机位',exact:true}).click();await page.getByLabel('预演秒数',{exact:true}).fill('2');
 await page.getByRole('button',{name:'保存场景',exact:true}).click();await page.getByText('已保存版本 1',{exact:true}).waitFor();const scene=(await call('get',root+'/director-scenes'))[0];report.scene=scene.id;const saved=await call('get',root+'/director-scenes/'+scene.id);assert.equal(saved.document.objects.length,4);assert.equal(saved.document.objects[0].position[0],-1.5);
 const canvas=page.locator('canvas[aria-label="导演台3D场景"]');await canvas.waitFor();await page.waitForTimeout(1200);await page.screenshot({path:`${out}/director-layout-dark.png`,animations:'disabled'});report.checks.push('Create interior template, adjust position, undo and save exact scene revision');
 await page.getByRole('button',{name:'相机取景',exact:true}).click();await page.getByLabel('预演进度',{exact:true}).fill('0.5');await page.waitForTimeout(400);await page.screenshot({path:`${out}/director-camera-dark.png`,animations:'disabled'});
 const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'下载取景图',exact:true}).click();await (await downloaded).saveAs(`${out}/camera-reference.png`);
 await page.getByLabel('参考回填镜头',{exact:true}).selectOption(report.shot);const pending=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/references'));await page.getByRole('button',{name:'加入镜头候选',exact:true}).click();const response=await pending;assert.ok(response.ok(),await response.text());const gen=await response.json();report.generation=gen.id;assert.equal(gen.input_refs.scene_id,scene.id);assert.equal(gen.input_refs.revision,1);assert.equal(gen.input_refs.progress,.5);assert.equal(gen.is_selected,false);report.checks.push('Actual WebGL PNG captured; reference returned to exact shot with pinned scene revision and no automatic selection');
 const video=page.waitForEvent('download',{timeout:30000});await page.getByRole('button',{name:'导出运镜视频',exact:true}).click();await (await video).saveAs(`${out}/camera-motion.mp4`);report.checks.push('Actual two-second camera movement rendered frame by frame and encoded as MP4');
 await page.getByLabel('预演名称',{exact:true}).fill('未保存的机位草稿');await page.reload();await page.getByRole('button',{name:'恢复草稿',exact:true}).click();await page.getByLabel('预演名称',{exact:true}).waitFor();assert.equal(await page.getByLabel('预演名称',{exact:true}).inputValue(),'未保存的机位草稿');await page.getByRole('button',{name:'保存场景',exact:true}).click();await page.getByText('已保存版本 2',{exact:true}).waitFor();report.checks.push('Reload recovers unsaved scene draft without losing server history');
 await page.getByRole('button',{name:'历史',exact:true}).click();await page.getByRole('button',{name:'恢复 v1',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'确定',exact:true}).click();await page.getByText('已保存 · v3',{exact:true}).waitFor();assert.equal(await page.getByLabel('预演名称',{exact:true}).inputValue(),'窗前对话 · 推近预演');report.checks.push('Persistent history restore creates new revision');
 await page.evaluate(()=>{document.documentElement.classList.remove('dark');document.documentElement.classList.add('light')});await page.waitForTimeout(300);await page.screenshot({path:`${out}/director-light.png`,animations:'disabled'});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);assert.ok(await page.locator('main').evaluate(e=>e.scrollWidth<=e.clientWidth));await page.screenshot({path:`${out}/director-mobile.png`,fullPage:true,animations:'disabled'});assert.deepEqual(errors,[]);report.errors=errors;report.passed=true;await writeFile(`${out}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(e){await page.screenshot({path:`${out}/failure.png`,fullPage:true});await writeFile(`${out}/failure.json`,JSON.stringify({...report,error:String(e),errors},null,2));throw e}finally{await browser.close()}
