import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
assert.equal(process.env.TEST_ISOLATED_PREVIEW,'1');
const base=process.env.APP_URL,out=process.env.ARTIFACT_DIR;await mkdir(out,{recursive:true});
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1560,height:1080}}),page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));const report={checks:[]};
try{
 const login=await context.request.post(`${base}/api/v1/auth/login`,{data:{username:'demo',password:'demo1234'}});assert.ok(login.ok());const token=(await login.json()).access_token,headers={Authorization:`Bearer ${token}`};
 const call=async(method,path,data)=>{const r=await context.request[method](`${base}/api/v1${path}`,{headers,data});assert.ok(r.ok(),await r.text());return r.json()};
 const p=await call('post','/projects',{code:'EVIDENCE-'+Date.now(),name:'身份验收 · 证据与纠错'}),root=`/projects/${p.id}`,ev=root+'/identity-evidence';report.project=p.id;
 const video=await readFile(process.env.VIDEO_FIXTURE);const upload=await call('post',root+'/library/uploads',{filename:'双人预演证据.mp4',size_bytes:video.length,fingerprint:createHash('sha256').update(video).digest('hex')});const version=upload.version??upload;report.version=version.id;report.media=version.media_id;
 const chunk=await context.request.post(`${base}/api/v1${root}/library/versions/${version.id}/chunk?offset=0`,{headers,multipart:{file:{name:'chunk',mimeType:'application/octet-stream',buffer:video}}});assert.ok(chunk.ok(),await chunk.text());await call('post',root+`/library/versions/${version.id}/complete`);
 let ready;for(let i=0;i<60;i++){ready=await call('get',root+`/library/versions/${version.id}`);if(ready.status==='ready'||ready.status==='failed')break;await page.waitForTimeout(500)}assert.equal(ready.status,'ready');
 await context.addInitScript(t=>{localStorage.setItem('inspiration_token',t);localStorage.setItem('inspiration_lang','zh')},token);
 await page.goto(`${base}${root}/evidence?version=${version.id}&start=100&end=1700`);await page.getByRole('button',{name:'新建角色身份',exact:true}).click();await page.getByLabel('角色姓名',{exact:true}).fill('林舟');await page.getByLabel('角色别名',{exact:true}).fill('小林');await page.getByRole('button',{name:'保存身份',exact:true}).click();await page.getByText('角色身份已保存',{exact:true}).waitFor();const a=(await call('get',ev+'/identities'))[0];report.identity=a.id;
 await page.getByLabel('证据关联身份',{exact:true}).selectOption(a.id);await page.getByLabel('证据状态',{exact:true}).selectOption('confirmed');await page.getByLabel('实际观察',{exact:true}).fill('金色替身站在桌子左侧，面对蓝色替身。');await page.getByLabel('判断依据',{exact:true}).fill('验收用人工标签，对应导演台中的人物 A。');const saved=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/identity-evidence'));await page.getByRole('button',{name:'保存观察',exact:true}).click();const r=await saved;assert.ok(r.ok());const evidence=await r.json();report.evidence=evidence.id;await page.getByRole('button',{name:/林舟.*已确认/}).click();await page.getByRole('button',{name:'修正历史',exact:true}).waitFor();await page.screenshot({path:`${out}/evidence-dark.png`,animations:'disabled'});
 let impact=await call('get',root+`/library/${version.media_id}/deletion-impact`);assert.equal(impact.evidence_count,1);assert.equal(impact.can_trash,false);report.checks.push('Real source uploaded and previewed; identity evidence pins version/time and protects source retention');
 await page.getByRole('button',{name:'纠正判断',exact:true}).click();await page.getByLabel('证据关联身份',{exact:true}).selectOption('');await page.getByLabel('判断依据',{exact:true}).fill('撤回身份判断，只能确认金色替身，不能据外观认定角色。');const corrected=page.waitForResponse(r=>r.request().method()==='PUT'&&r.url().endsWith('/'+evidence.id));await page.getByRole('button',{name:'保存更正',exact:true}).click();assert.ok((await corrected).ok());assert.equal((await call('get',ev+`?identity_id=${a.id}`)).total,0);assert.equal((await call('get',ev+'?unknown=true')).total,1);await page.getByRole('button',{name:'未知身份 · 待辨认',exact:true}).click();await page.getByRole('button',{name:/未知身份.*已确认/}).click();await page.getByRole('button',{name:'修正历史',exact:true}).click();await page.getByRole('button',{name:'恢复',exact:true}).last().click();await page.getByRole('alertdialog').getByRole('button',{name:'确定',exact:true}).click();await page.getByText('历史判断已恢复为新修订',{exact:true}).waitFor();assert.equal((await call('get',ev+`?identity_id=${a.id}`)).total,1);report.checks.push('Correct identity to unknown updates retrieval; immutable history restores original identity as new revision');
 const b=await call('post',ev+'/identities',{name:'周岚'});const item={version_id:version.id,start_ms:100,end_ms:1700,identity_id:b.id,status:'confirmed',kind:'speech',observation:'验收用台词提及示例（非实际音轨）'};await call('post',ev,item);assert.equal((await call('get',ev+`?identity_id=${a.id}&with_identity=${b.id}`)).total,0);await call('post',ev,{...item,kind:'visual',observation:'蓝色替身站在桌子右侧。'});assert.equal((await call('get',ev+`?identity_id=${a.id}&with_identity=${b.id}`)).total,1);report.checks.push('Dialogue mentions excluded from confirmed visual-overlap search; explicit visual evidence can match');
 await page.reload();await page.getByRole('button',{name:/林舟 小林/}).click();await page.getByLabel('重叠出现身份',{exact:true}).selectOption(b.id);await page.getByRole('button',{name:/林舟.*已确认/}).click();await page.locator('video[aria-label="查看原片证据"]').waitFor();await page.evaluate(()=>{document.documentElement.classList.remove('dark');document.documentElement.classList.add('light')});await page.waitForTimeout(250);await page.screenshot({path:`${out}/evidence-light.png`,animations:'disabled'});await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('main').evaluate(e=>e.scrollWidth<=e.clientWidth));await page.screenshot({path:`${out}/evidence-mobile.png`,fullPage:true,animations:'disabled'});assert.deepEqual(errors,[]);report.errors=errors;report.passed=true;await writeFile(`${out}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(e){await page.screenshot({path:`${out}/failure.png`,fullPage:true});await writeFile(`${out}/failure.json`,JSON.stringify({...report,error:String(e),errors},null,2));throw e}finally{await browser.close()}
