import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
assert.equal(process.env.TEST_ISOLATED_PREVIEW,'1');
const base=process.env.APP_URL,out=process.env.ARTIFACT_DIR;await mkdir(out,{recursive:true});
const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_MODULE).href);
const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1560,height:1080},acceptDownloads:true}),page=await context.newPage(),errors=[],report={checks:[],sources:[]};page.on('pageerror',e=>errors.push(e.message));
try{
 const login=await context.request.post(`${base}/api/v1/auth/login`,{data:{username:'demo',password:'demo1234'}});assert.ok(login.ok());const token=(await login.json()).access_token,headers={Authorization:`Bearer ${token}`};
 const call=async(method,path,data)=>{const r=await context.request[method](`${base}/api/v1${path}`,{headers,data});assert.ok(r.ok(),await r.text());return r.json()};
 const p=await call('post','/projects',{code:'ASR-'+Date.now(),name:'转写验收 · 中英文与字幕草稿'}),root=`/projects/${p.id}`;report.project=p.id;await context.addInitScript(t=>{localStorage.setItem('inspiration_token',t);localStorage.setItem('inspiration_lang','zh')},token);
 for(const [name,language] of [['chinese-synthetic','zh'],['english-public-speech','en']]){
  const buffer=await readFile(`${out}/${name}.mp4`);const v=await call('post',root+'/library/uploads',{filename:name+'.mp4',size_bytes:buffer.length,fingerprint:createHash('sha256').update(buffer).digest('hex')});const response=await context.request.post(`${base}/api/v1${root}/library/versions/${v.id}/chunk?offset=0`,{headers,multipart:{file:{name:'chunk',mimeType:'application/octet-stream',buffer}}});assert.ok(response.ok(),await response.text());await call('post',root+`/library/versions/${v.id}/complete`);let version;
  for(let i=0;i<120;i++){version=await call('get',root+`/library/versions/${v.id}`);if(['ready','failed'].includes(version.status))break;await page.waitForTimeout(500)}assert.equal(version.status,'ready');
  await page.goto(`${base}${root}/transcriptions?version=${v.id}`);await page.getByLabel('转写语言',{exact:true}).selectOption(language);const waiting=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/transcriptions'));await page.getByRole('button',{name:'开始转写',exact:true}).click();const submitted=await waiting;assert.ok(submitted.ok(),await submitted.text());let run=await submitted.json();console.log(name+' transcription queued');
  for(let i=0;i<300;i++){run=await call('get',root+`/transcriptions/${run.id}`);if(['ready','failed','canceled'].includes(run.status))break;await page.waitForTimeout(1000)}assert.equal(run.status,'ready',JSON.stringify(run));const transcript=run.cues.map(c=>c.text).join(' ');assert.ok(run.cues.length);assert.ok(run.cues.every(c=>c.start_ms>=0&&c.end_ms<=version.duration_ms));
  if(language==='zh')assert.ok(transcript.includes('海')&&transcript.includes('蓝色'),transcript);else assert.ok(transcript.toLowerCase().includes('country'),transcript);
  report.sources.push({name,language,version:v.id,run:run.id,duration_ms:version.duration_ms,original_cues:run.cues,model_key:run.model_key});console.log(name+' real ASR complete');
  assert.equal((await call('get',root+`/library/versions/${v.id}/annotations`)).total,0);
  if(language==='zh'){
   await page.getByLabel('字幕 1 内容',{exact:true}).waitFor();await page.getByRole('button',{name:'播放字幕 1',exact:true}).click();const video=page.locator('video[aria-label="字幕对应音轨片段"]');await page.waitForFunction(()=>document.querySelector('video[aria-label="字幕对应音轨片段"]')?.readyState>=2,{},{timeout:30000});await page.screenshot({path:`${out}/transcription-dark.png`,animations:'disabled'});
   await page.getByLabel('字幕 1 内容',{exact:true}).fill('清晨，海边的小屋亮起了灯。');await page.getByRole('button',{name:'保存字幕',exact:true}).click();await page.getByText('字幕草稿已保存',{exact:true}).waitFor();const actual=await call('get',root+`/transcriptions/${run.id}`);assert.equal(actual.revision,1);assert.equal(actual.cues[0].text,'清晨，海边的小屋亮起了灯。');
   await page.getByRole('button',{name:'核对完成，发布到检索',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'确定',exact:true}).click();await page.getByText('核对后的字幕已发布到台词检索',{exact:true}).waitFor();const annotations=await call('get',root+`/library/versions/${v.id}/annotations`);assert.equal(annotations.total,actual.cues.length);assert.ok(annotations.items.every(a=>a.kind==='speech'&&a.source.reviewed));
   const found=await call('post',root+'/library/search',{mode:'annotated',query:'海边的小屋',kind:'speech'});assert.equal(found.total,1);const notVisual=await call('post',root+'/library/search',{mode:'annotated',query:'海边的小屋',kind:'visual'});assert.equal(notVisual.total,0);
   const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出 SRT',exact:true}).click();await (await download).saveAs(`${out}/reviewed-chinese.srt`);assert.ok((await readFile(`${out}/reviewed-chinese.srt`,'utf8')).includes('海边的小屋'));report.checks.push('Chinese synthetic speech transcribed with real model; editable draft remains outside search until review publication; SRT export and speech-only search verified');
   await page.evaluate(()=>{document.documentElement.classList.remove('dark');document.documentElement.classList.add('light')});await page.waitForTimeout(250);await page.screenshot({path:`${out}/transcription-light.png`,animations:'disabled'});await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('main').evaluate(e=>e.scrollWidth<=e.clientWidth));await page.screenshot({path:`${out}/transcription-mobile.png`,fullPage:true,animations:'disabled'});await page.setViewportSize({width:1560,height:1080});
  }
 }
 report.checks.push('Public English speech transcribed with real model and valid original-media timing');assert.deepEqual(errors,[]);report.errors=errors;report.passed=true;await writeFile(`${out}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report));
}catch(e){await page.screenshot({path:`${out}/failure.png`,fullPage:true});await writeFile(`${out}/failure.json`,JSON.stringify({...report,error:String(e),errors},null,2));throw e}finally{await browser.close()}
